-- Run this query in your Supabase SQL Editor

create table leaderboard (
  id bigint generated by default as identity primary key,
  name text not null,
  score int not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Optional: Create an index on score for faster sorting if you expect many entries
create index leaderboard_score_idx on leaderboard (score desc);
